draw_text(oplayerm.x - 64, oplayerm.y - 85, "hh: " + string(oplayerm.hh))
//draw_text(oplayerm.x - 64, oplayerm.y - 100, "y: " + string(otb.y))
draw_text(oplayerm.x - 64, oplayerm.y - 115, "m: " + string(oplayerm.m))
draw_text(oplayerm.x - 64, oplayerm.y - 130, "bb: " + string(oplayerm.count))
//draw_text(oplayerm.x - 64, oplayerm.y - 145, "x: " + string(otb.x))
//draw_text(oplayer.x - 64, oplayer.y - 160, "parabola len: " + string(oplayer.pl))
//draw_text(oplayer.x - 64, oplayer.y - 175, "upwards momentum: " + string(oplayer.um))
//draw_text(oplayer.x - 64, oplayer.y - 200, "input rate: " + string(oplayer.ir))
//draw_text(oplayer.x - 64, oplayer.y - 215, "wall: " + string(oplayer.wall))
//draw_text(oplayer.x - 64, oplayer.y - 230, "h: " + string(oplayer.l))