draw_text(oplayer.x - 64, oplayer.y - 85, "in air: " + string(oplayer.air))
draw_text(oplayer.x - 64, oplayer.y - 100, "g: " + string(oplayer.g))
draw_text(oplayer.x - 64, oplayer.y - 115, "horizontal: " + string(oplayer.h))
draw_text(oplayer.x - 64, oplayer.y - 130, "horizontal cap: " + string(oplayer.hc))
draw_text(oplayer.x - 64, oplayer.y - 145, "horizontal direction: " + string(oplayer.hd))
draw_text(oplayer.x - 64, oplayer.y - 160, "parabola len: " + string(oplayer.pl))
draw_text(oplayer.x - 64, oplayer.y - 175, "upwards momentum: " + string(oplayer.um))
draw_text(oplayer.x - 64, oplayer.y - 200, "input rate: " + string(oplayer.ir))
draw_text(oplayer.x - 64, oplayer.y - 215, "um: " + string(oplayer.um))
draw_text(oplayer.x - 64, oplayer.y - 230, "ir: " + string(oplayer.ir))